# permissions for end users to edit whoamis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whoami-editor-role
rules:
- apiGroups:
  - identity.k8s.appscode.com
  resources:
  - whoamis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.k8s.appscode.com
  resources:
  - whoamis/status
  verbs:
  - get
